### ISSUE TITLE
trick

### ISSUE THREAD

**Issue by a-detiste** [dgibbs64/SteamCMD-Commands-List#1]
why not simply  `find :` ?

**Comment by dgibbs64** [comment]
Tested this. Only gave me a small output and not the whole list

      Steam>find :
      ConVars:
                   @sSteamCmdForcePlatformType = ""           : Must be one of: [windows | macos | linux]
                @sSteamCmdForcePlatformBitness = ""           : Must be one of: [32 | 64]
      Commands:
                                        app_stop : <appid> [force:0|1] stop this running app
                                licenses_for_app : <appid> : shows active licenses for appid
                                 app_info_update : [0|1] : trigger app info update, optionally for update all
                                   log_callbacks : usage: "log_callbacks <first callbackID> [last callbackID]
                                         log_ipc : usage: "log_ipc [counts|verbose] <filter>" Enables IPC logging. Specifying "counts" or "verbose" is optional, defaulting to counts.
                                        p2p_info : usage: "p2p_info" Displays the current state of the P2P networking subsystem.
                        dump_scheduled_functions : usage: "dump_scheduled_functions" Displays internal Steam function callback timers
                        upload_controller_config : upload_controller_config <appid> <filename> : upload controller config to cloud
                                  download_depot : download_depot <appid> <depotid> : download a single depot
                                      verify_vpk : verify_vpk <datafile> : verifies content of given VPK
                              verify_chunk_store : verify_chunk_store <appid> <depotid> <datafile> : run app depot build as specified in appbuildfile
                              run_app_build_http : run_app_build_http : alias for run_app_build
                                   run_app_build : run_app_build [-preview] [-desc <text>] <appbuildfile> : run app depot build as specified in appbuildfile
                            app_build_all_depots : app_build_all_depots [-desc <text>] -depotconfigpath <folder> -contentroot <folder> -buildoutput <folder> <appid>  : Build all depots for one app
                                     api_logging : api_logging <enabled> <verbose> : enable/disable verbose API logging in steamcmd
                                        ceg_wrap : ceg_wrap <appid> <orig filename> <stripped filename> <strips filename> : upload executable to back end for CEG wrapping
                                        drm_wrap : drm_wrap <appid> <input filename> <output filename> <toolname> <flags> : upload executable to back end for DRM wrapping
                             sign_install_script : sign_install_script <appid> <input filename> <output filename> : upload install script to back end for signing
                          workshop_download_item : workshop_download_item <appid> <PublishedFileId> : download a workshop item
                     workshop_create_legacy_item : workshop_create_legacy_item <appid> <workshop file> : build a legacy workshop item
                             workshop_build_item : workshop_build_item <build config filename> : build a workshop item

**Comment by a-detiste** [comment]
yup, can't reproduce this either
